### ISSUE TITLE
Fetching the high water mark can abend in CloudFormation if stack has been idle for a period of time

### ISSUE THREAD

**Issue by antaenc** [Senzing/governor-postgresql-transaction-id#19]
When a stack is up for a period of time with inactivity an abend in senzing_governor.py can occur resulting in all subsequent SQS messages being placed on the dead letter queue. RDS logs weren't available when checking, suspect a timeout on connections in the governor causing the error on cursor. This was seen after a config change via G2ConfigTool was applied within the stack and numerous hours passing before the data source the config was for was pushed to SQS. 

```
2021-01-22T10:16:43.657-05:00	Exception in thread ReadSqsWriteG2Thread-o-thread-5:
2021-01-22T10:16:43.658-05:00	Traceback (most recent call last):
2021-01-22T10:16:43.658-05:00	File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
2021-01-22T10:16:43.658-05:00	self.run()
2021-01-22T10:16:43.658-05:00	File "/app/stream-loader.py", line 2028, in run
2021-01-22T10:16:43.658-05:00	self.govern()
2021-01-22T10:16:43.658-05:00	File "/app/stream-loader.py", line 1249, in govern
2021-01-22T10:16:43.658-05:00	return self.governor.govern() 
2021-01-22T10:16:43.658-05:00	File "/opt/senzing/g2/python/senzing_governor.py", line 307, in govern 
2021-01-22T10:16:43.658-05:00	watermark = self.get_current_watermark(cursor, database_name) 
2021-01-22T10:16:43.658-05:00	File "/opt/senzing/g2/python/senzing_governor.py", line 191, in get_current_watermark 
2021-01-22T10:16:43.658-05:00	cursor.execute(self.sql_stmt, [database_name]) 
2021-01-22T10:16:43.658-05:00	psycopg2. InterfaceError: cursor already closed
```

Restarting the ECS task for stream-loader and re-populsting the queue allowed SQS records to be correctly ingested, i.e., governor re-established connections and cursors in the DB cluster. 

senzing_governor.py needs error handling within self.get_current_watermark() to catch connection/cursor issues. If detected, attempt re-establishing connections and cursors at least once and re-trying the execute(). This will also need the DB code in init() moved to a function for reuse. If still fails need to gracefully raise to stream-loader for appropriate handling.

**Comment by docktermj** [comment]
This may no longer be needed when https://github.com/Senzing/governor-postgresql-transaction-id/issues/20 is delivered.

**Comment by docktermj** [comment]
@roncewind I'm thinking your new version might fix this issue.  I'll assign it to you.
